RecSys - Improve caching
railroadmedia/railcontent pull request #62
Opened 2024-04-09 16:46 UTC by adrian-musora

MWP PR: https://github.com/railroadmedia/musora-web-platform/pull/846

2024-04-10 14:11 UTC, roxanariza requested changes

2024-04-10 14:11 UTC, roxanariza commented on src/Services/ContentService.php
> -    private $contentRepository;
Please revert these updates. All the catalogs and other pages are crashing now

2024-04-10 14:11 UTC, roxanariza commented on src/Services/ContentService.php
> -        $this->contentRepository = $contentRepository;
Revert please

2024-04-10 15:46 UTC, adrian-musora commented on src/Services/ContentService.php
> -    private $contentRepository;
Merged with 2.0- and crashes are resolved.

2024-04-11 12:28 UTC, roxanariza commented on src/Services/ContentService.php
> -    private $contentRepository;
Issues are fixed now! Thanks!

2024-04-11 12:28 UTC, roxanariza commented on src/Services/ContentService.php
> -        $this->contentRepository = $contentRepository;
Issues are fixed now! Thanks!

2024-04-11 12:29 UTC, roxanariza approved these changes

2024-04-11 15:08 UTC, merged